from __future__ import annotations

import threading
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

import chromadb
from chromadb.api.models.Collection import Collection

from app.core.config import settings
from app.core.logger import logger


Metadata = dict[str, str | int | float | bool]


class ChromaService:
    """
    Shared service for persistent ChromaDB access.

    Responsibilities:
    - Initialize one persistent ChromaDB client per process.
    - Maintain one application collection.
    - Insert document chunks and embeddings.
    - Perform similarity searches with optional metadata filters.
    - Delete vectors by ID, document, or metadata filter.
    - Expose basic collection statistics.

    Embeddings are generated by EmbeddingService. ChromaDB is used only
    for vector storage and retrieval.
    """

    _client: Any | None = None
    _collection: Collection | None = None

    _initialization_lock = threading.Lock()

    def __init__(self) -> None:
        self._ensure_initialized()

        if (
            self.__class__._client is None
            or self.__class__._collection is None
        ):
            raise RuntimeError(
                "ChromaDB initialization did not complete successfully."
            )

        self.client = self.__class__._client
        self.collection = self.__class__._collection

    # ==========================================================
    # Initialization
    # ==========================================================

    @classmethod
    def _ensure_initialized(cls) -> None:
        """
        Initialize the persistent client and collection once per process.
        """

        if cls._client is not None and cls._collection is not None:
            return

        with cls._initialization_lock:
            if cls._client is not None and cls._collection is not None:
                return

            db_path = Path(settings.CHROMA_DB_DIR).expanduser()

            try:
                db_path.mkdir(
                    parents=True,
                    exist_ok=True,
                )

                logger.info(
                    "Initializing ChromaDB at %s.",
                    db_path,
                )

                client = chromadb.PersistentClient(
                    path=str(db_path),
                )

                collection = client.get_or_create_collection(
                    name=settings.CHROMA_COLLECTION_NAME,
                    metadata={
                        "hnsw:space": "cosine",
                    },
                )

            except Exception:
                logger.exception(
                    "Failed to initialize ChromaDB."
                )
                raise

            cls._client = client
            cls._collection = collection

            logger.info(
                "ChromaDB initialized successfully. "
                "Collection='%s', vectors=%d.",
                collection.name,
                collection.count(),
            )

    # ==========================================================
    # Validation
    # ==========================================================

    @staticmethod
    def _validate_embedding(
        embedding: Sequence[float],
        *,
        field_name: str,
    ) -> None:
        """
        Validate that an embedding is non-empty and numeric.
        """

        if not embedding:
            raise ValueError(
                f"{field_name} cannot be empty."
            )

        if any(
            not isinstance(value, (int, float))
            for value in embedding
        ):
            raise TypeError(
                f"{field_name} must contain only numeric values."
            )

    @staticmethod
    def _validate_metadata(
        metadata: Mapping[str, Any],
    ) -> None:
        """
        Validate metadata before sending it to ChromaDB.
        """

        allowed_types = (
            str,
            int,
            float,
            bool,
        )

        for key, value in metadata.items():
            if not isinstance(key, str) or not key.strip():
                raise ValueError(
                    "Metadata keys must be non-empty strings."
                )

            if not isinstance(value, allowed_types):
                raise TypeError(
                    f"Unsupported metadata value for '{key}': "
                    f"{type(value).__name__}."
                )

    # ==========================================================
    # Insert
    # ==========================================================

    def add_documents(
        self,
        ids: list[str],
        documents: list[str],
        embeddings: list[list[float]],
        metadatas: list[Metadata] | None = None,
    ) -> None:
        """
        Add document chunks and their embeddings to ChromaDB.

        Every ID, document, embedding, and metadata entry must refer
        to the same chunk position.
        """

        if not ids:
            raise ValueError(
                "At least one document chunk is required."
            )

        if not documents:
            raise ValueError(
                "Documents cannot be empty."
            )

        if not embeddings:
            raise ValueError(
                "Embeddings cannot be empty."
            )

        lengths = {
            "ids": len(ids),
            "documents": len(documents),
            "embeddings": len(embeddings),
        }

        if metadatas is not None:
            lengths["metadatas"] = len(metadatas)

        if len(set(lengths.values())) != 1:
            raise ValueError(
                "ChromaDB input lengths do not match: "
                f"{lengths}."
            )

        normalized_ids: list[str] = []
        normalized_documents: list[str] = []

        seen_ids: set[str] = set()

        for index, vector_id in enumerate(ids):
            vector_id = vector_id.strip()

            if not vector_id:
                raise ValueError(
                    f"Vector ID at index {index} cannot be empty."
                )

            if vector_id in seen_ids:
                raise ValueError(
                    f"Duplicate vector ID: {vector_id}."
                )

            seen_ids.add(vector_id)
            normalized_ids.append(vector_id)

        for index, document in enumerate(documents):
            document = document.strip()

            if not document:
                raise ValueError(
                    f"Document at index {index} cannot be empty."
                )

            normalized_documents.append(document)

        embedding_dimension: int | None = None

        for index, embedding in enumerate(embeddings):
            self._validate_embedding(
                embedding,
                field_name=f"Embedding at index {index}",
            )

            if embedding_dimension is None:
                embedding_dimension = len(embedding)

            elif len(embedding) != embedding_dimension:
                raise ValueError(
                    "All embeddings must have the same dimension."
                )

        if metadatas is not None:
            for metadata in metadatas:
                self._validate_metadata(metadata)

        try:
            self.collection.add(
                ids=normalized_ids,
                documents=normalized_documents,
                embeddings=embeddings,
                metadatas=metadatas,
            )

            logger.info(
                "Added %d chunks to ChromaDB collection '%s'.",
                len(normalized_ids),
                self.collection.name,
            )

        except Exception:
            logger.exception(
                "Failed to add %d chunks to ChromaDB.",
                len(normalized_ids),
            )
            raise

    # ==========================================================
    # Search
    # ==========================================================

    def search(
        self,
        query_embedding: list[float],
        n_results: int = 5,
        where: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """
        Perform a similarity search.

        The optional ``where`` filter should be used for ownership
        and document-level isolation, for example:

            {"user_id": 4}

        or:

            {
                "$and": [
                    {"user_id": 4},
                    {"document_id": 31},
                ]
            }
        """

        self._validate_embedding(
            query_embedding,
            field_name="Query embedding",
        )

        if n_results <= 0:
            raise ValueError(
                "n_results must be greater than zero."
            )

        if where is not None and not isinstance(where, dict):
            raise TypeError(
                "where must be a dictionary or None."
            )

        try:
            query_kwargs: dict[str, Any] = {
                "query_embeddings": [
                    query_embedding,
                ],
                "n_results": n_results,
                "include": [
                    "documents",
                    "metadatas",
                    "distances",
                ],
            }

            if where is not None:
                query_kwargs["where"] = where

            result = self.collection.query(
                **query_kwargs,
            )

            logger.debug(
                "ChromaDB search completed. "
                "Requested results=%d, filter=%s.",
                n_results,
                where,
            )

            return result

        except Exception:
            logger.exception(
                "ChromaDB similarity search failed."
            )
            raise

    # ==========================================================
    # Delete by vector IDs
    # ==========================================================

    def delete_documents(
        self,
        ids: list[str],
    ) -> int:
        """
        Delete vectors by their ChromaDB IDs.

        Returns the number of requested vector IDs.
        """

        normalized_ids = [
            vector_id.strip()
            for vector_id in ids
            if vector_id and vector_id.strip()
        ]

        if not normalized_ids:
            return 0

        normalized_ids = list(
            dict.fromkeys(normalized_ids)
        )

        try:
            self.collection.delete(
                ids=normalized_ids,
            )

            logger.info(
                "Deleted %d requested vectors from ChromaDB.",
                len(normalized_ids),
            )

            return len(normalized_ids)

        except Exception:
            logger.exception(
                "Failed to delete vectors from ChromaDB."
            )
            raise

    # ==========================================================
    # Delete by metadata
    # ==========================================================

    def delete_by_metadata(
        self,
        where: dict[str, Any],
    ) -> int:
        """
        Delete all vectors matching a metadata filter.

        Returns the number of matching vectors found before deletion.
        """

        if not where:
            raise ValueError(
                "A metadata filter is required for deletion."
            )

        try:
            result = self.collection.get(
                where=where,
                include=[],
            )

            ids = result.get("ids") or []

            if not ids:
                return 0

            self.collection.delete(
                ids=ids,
            )

            logger.info(
                "Deleted %d vectors using metadata filter %s.",
                len(ids),
                where,
            )

            return len(ids)

        except Exception:
            logger.exception(
                "Failed to delete vectors using metadata filter."
            )
            raise

    # ==========================================================
    # Delete document chunks
    # ==========================================================

    def delete_document_chunks(
        self,
        document_id: int,
        user_id: int | None = None,
    ) -> int:
        """
        Delete all chunks belonging to a document.

        If user_id is supplied, both document ownership and document ID
        must match. Supplying user_id is preferred for user-facing flows.
        """

        if document_id <= 0:
            raise ValueError(
                "document_id must be greater than zero."
            )

        if user_id is not None and user_id <= 0:
            raise ValueError(
                "user_id must be greater than zero."
            )

        if user_id is None:
            where: dict[str, Any] = {
                "document_id": document_id,
            }

        else:
            where = {
                "$and": [
                    {
                        "document_id": document_id,
                    },
                    {
                        "user_id": user_id,
                    },
                ]
            }

        deleted_count = self.delete_by_metadata(
            where=where,
        )

        logger.info(
            "Deleted %d chunks for document %d.",
            deleted_count,
            document_id,
        )

        return deleted_count

    # ==========================================================
    # Statistics
    # ==========================================================

    def count(self) -> int:
        """
        Return the number of vectors in the collection.
        """

        try:
            return self.collection.count()

        except Exception:
            logger.exception(
                "Failed to count ChromaDB vectors."
            )
            raise

    def is_empty(self) -> bool:
        """
        Return whether the collection contains no vectors.
        """

        return self.count() == 0

    def collection_info(self) -> dict[str, Any]:
        """
        Return basic information about the active collection.
        """

        return {
            "name": self.collection.name,
            "count": self.count(),
        }