"""sync document indexes and default

Revision ID: bd6424f1ec7b
Revises: 888642df3b46
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6424f1ec7b'
down_revision: Union[str, Sequence[str], None] = '888642df3b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'chroma_collection',
               existing_type=sa.VARCHAR(),
               server_default='documents',
               existing_nullable=False)
    op.create_index(op.f('ix_documents_file_type'), 'documents', ['file_type'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_type'), table_name='documents')
    op.alter_column('documents', 'chroma_collection',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
