"""add mode to chat history

Revision ID: c45910dad343
Revises: bd6424f1ec7b
Create Date: 2026-07-30 07:46:56.319111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45910dad343'
down_revision: Union[str, Sequence[str], None] = 'bd6424f1ec7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('mode', sa.String(length=20), server_default='document', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'mode')
    # ### end Alembic commands ###
